//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSoap.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Handler.dhamarmj.pucmm.edu/", ConfigurationName="ServiceReference1.UrlWebService")]
    public interface UrlWebService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Handler.dhamarmj.pucmm.edu/UrlWebService/getUrlRequest", ReplyAction="http://Handler.dhamarmj.pucmm.edu/UrlWebService/getUrlResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientSoap.ServiceReference1.getUrlResponse getUrl(ClientSoap.ServiceReference1.getUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Handler.dhamarmj.pucmm.edu/UrlWebService/getUrlRequest", ReplyAction="http://Handler.dhamarmj.pucmm.edu/UrlWebService/getUrlResponse")]
        System.Threading.Tasks.Task<ClientSoap.ServiceReference1.getUrlResponse> getUrlAsync(ClientSoap.ServiceReference1.getUrlRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Handler.dhamarmj.pucmm.edu/UrlWebService/helloWorldRequest", ReplyAction="http://Handler.dhamarmj.pucmm.edu/UrlWebService/helloWorldResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientSoap.ServiceReference1.helloWorldResponse helloWorld(ClientSoap.ServiceReference1.helloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Handler.dhamarmj.pucmm.edu/UrlWebService/helloWorldRequest", ReplyAction="http://Handler.dhamarmj.pucmm.edu/UrlWebService/helloWorldResponse")]
        System.Threading.Tasks.Task<ClientSoap.ServiceReference1.helloWorldResponse> helloWorldAsync(ClientSoap.ServiceReference1.helloWorldRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Handler.dhamarmj.pucmm.edu/")]
    public partial class urlSoap : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string redirectField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string redirect {
            get {
                return this.redirectField;
            }
            set {
                this.redirectField = value;
                this.RaisePropertyChanged("redirect");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUrl", WrapperNamespace="http://Handler.dhamarmj.pucmm.edu/", IsWrapped=true)]
    public partial class getUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Handler.dhamarmj.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public getUrlRequest() {
        }
        
        public getUrlRequest(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUrlResponse", WrapperNamespace="http://Handler.dhamarmj.pucmm.edu/", IsWrapped=true)]
    public partial class getUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Handler.dhamarmj.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientSoap.ServiceReference1.urlSoap[] @return;
        
        public getUrlResponse() {
        }
        
        public getUrlResponse(ClientSoap.ServiceReference1.urlSoap[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloWorld", WrapperNamespace="http://Handler.dhamarmj.pucmm.edu/", IsWrapped=true)]
    public partial class helloWorldRequest {
        
        public helloWorldRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloWorldResponse", WrapperNamespace="http://Handler.dhamarmj.pucmm.edu/", IsWrapped=true)]
    public partial class helloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Handler.dhamarmj.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloWorldResponse() {
        }
        
        public helloWorldResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UrlWebServiceChannel : ClientSoap.ServiceReference1.UrlWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UrlWebServiceClient : System.ServiceModel.ClientBase<ClientSoap.ServiceReference1.UrlWebService>, ClientSoap.ServiceReference1.UrlWebService {
        
        public UrlWebServiceClient() {
        }
        
        public UrlWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UrlWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrlWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrlWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientSoap.ServiceReference1.getUrlResponse ClientSoap.ServiceReference1.UrlWebService.getUrl(ClientSoap.ServiceReference1.getUrlRequest request) {
            return base.Channel.getUrl(request);
        }
        
        public ClientSoap.ServiceReference1.urlSoap[] getUrl(long arg0) {
            ClientSoap.ServiceReference1.getUrlRequest inValue = new ClientSoap.ServiceReference1.getUrlRequest();
            inValue.arg0 = arg0;
            ClientSoap.ServiceReference1.getUrlResponse retVal = ((ClientSoap.ServiceReference1.UrlWebService)(this)).getUrl(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientSoap.ServiceReference1.getUrlResponse> ClientSoap.ServiceReference1.UrlWebService.getUrlAsync(ClientSoap.ServiceReference1.getUrlRequest request) {
            return base.Channel.getUrlAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientSoap.ServiceReference1.getUrlResponse> getUrlAsync(long arg0) {
            ClientSoap.ServiceReference1.getUrlRequest inValue = new ClientSoap.ServiceReference1.getUrlRequest();
            inValue.arg0 = arg0;
            return ((ClientSoap.ServiceReference1.UrlWebService)(this)).getUrlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientSoap.ServiceReference1.helloWorldResponse ClientSoap.ServiceReference1.UrlWebService.helloWorld(ClientSoap.ServiceReference1.helloWorldRequest request) {
            return base.Channel.helloWorld(request);
        }
        
        public string helloWorld() {
            ClientSoap.ServiceReference1.helloWorldRequest inValue = new ClientSoap.ServiceReference1.helloWorldRequest();
            ClientSoap.ServiceReference1.helloWorldResponse retVal = ((ClientSoap.ServiceReference1.UrlWebService)(this)).helloWorld(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientSoap.ServiceReference1.helloWorldResponse> ClientSoap.ServiceReference1.UrlWebService.helloWorldAsync(ClientSoap.ServiceReference1.helloWorldRequest request) {
            return base.Channel.helloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientSoap.ServiceReference1.helloWorldResponse> helloWorldAsync() {
            ClientSoap.ServiceReference1.helloWorldRequest inValue = new ClientSoap.ServiceReference1.helloWorldRequest();
            return ((ClientSoap.ServiceReference1.UrlWebService)(this)).helloWorldAsync(inValue);
        }
    }
}
